### PR TITLE
Css

### PR DESCRIPTION
**Pull request by vasystus**

### CODE REVIEW

**Comment by sonianb** [comment]
It looks like there's a "}" missing at the end of the css file. 
Also, I think the class naming got lost somewhere in between our merge conflicts huh😅 Should probably rename the delete classes on lines 17 and 18 to match the css selectors. But I tried to do that and this is what I'm getting. Not sure why but I think we're getting close to fixing this! :D

image

**Comment by lascellesabercrombie** [comment]
Still some issues for me

image

**Comment by lascellesabercrombie** [comment]
> Still some issues for me
> 
> image

This was with me trying to reconcile it with changes to main on my own server and reintroducing classes to server.js that had got lost

**Comment by lascellesabercrombie** [comment]
I found an unclosed section! It now looks like it's behaving. I'm going to push these changes to this branch and then we might be able to merge

Screenshot 2022-05-13 at 09 38 22

**Comment by lascellesabercrombie** [comment]
Looking great!

**Pull request merged**
